src/Entity/Membre.php
<?php

namespace App\Entity;

use App\Repository\MembreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MembreRepository::class)]
class Membre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 30)]
    private ?string $Nom = null;

    #[ORM\Column(length: 30)]
    private ?string $prenom = null;

    #[ORM\OneToMany(mappedBy: 'proprietaire', targetEntity: Salle::class, orphanRemoval: true,cascade: ["persist"])]
    private Collection $salles;

    #[ORM\OneToMany(mappedBy: 'membre', targetEntity: Hall::class)]
    private Collection $halls;

    #[ORM\OneToOne(inversedBy: 'membre', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $User = null;

  

    public function __construct()
    {
        $this->salles = new ArrayCollection();
        $this->halls = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * @return Collection<int, Salle>
     */
    public function getSalles(): Collection
    {
        return $this->salles;
    }

    public function addSalle(Salle $salle): self
    {
        if (!$this->salles->contains($salle)) {
            $this->salles->add($salle);
            $salle->setProprietaire($this);
        }

        return $this;
    }

    public function removeSalle(Salle $salle): self
    {
        if ($this->salles->removeElement($salle)) {
            // set the owning side to null (unless already changed)
            if ($salle->getProprietaire() === $this) {
                $salle->setProprietaire(null);
            }
        }

        return $this;
    }
    public function __toString() 
    {
        return $this->Nom ;
    }

    /**
     * @return Collection<int, Hall>
     */
    public function getHalls(): Collection
    {
        return $this->halls;
    }

    public function addHall(Hall $hall): self
    {
        if (!$this->halls->contains($hall)) {
            $this->halls->add($hall);
            $hall->setMembre($this);
        }

        return $this;
    }

    public function removeHall(Hall $hall): self
    {
        if ($this->halls->removeElement($hall)) {
            // set the owning side to null (unless already changed)
            if ($hall->getMembre() === $this) {
                $hall->setMembre(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(User $User): self
    {
        $this->User = $User;

        return $this;
    }

   

   
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
         <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">

        {% block stylesheets %}
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{{ asset('css/styles.css', 'startbootstrap') }}" rel="stylesheet">
        {% endblock %} {# stylesheets #}
    </head>
    <body>
    {% block menu %}
     <!-- Navigation -->
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
           <a class="navbar-brand" href="{{ path('app_salle_index') }}">salle</a>
           <a class="navbar-brand" href="{{ path('app_materiel_index') }}">Materiel</a>
           <a class="navbar-brand" href="{{ path('app_hall_index') }}">Hall</a>
            <a class="navbar-brand" href="{{ path('app_membre_index') }}">Membre</a>
           <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
           <div class="collapse navbar-collapse" id="navbarSupportedContent">
     <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
               {{ render_bootstrap_menu('main') }}
          {% if app.user %}
               {{ render_bootstrap_menu('account') }}
          {% else %}
               {{ render_bootstrap_menu('anonymousaccount') }}
          {% endif %}
     </ul>
</div>
         </div>
        
      </nav>
    {% endblock %}{# menu #}
        {% block body %}   
         <div class="container body-container">

    <main>

      {# Ici la partie utile que les gabarits des pages vont surcharger #}
      {% block main %}
      <div class="row">
        <div class="col-md-12">
          <p>
            <i>MAIN</i>
          </p>
        </div>
      </div>
      {% endblock %} {# main #}

    </main>

  </div> <!-- /.body-container -->

  {% block footer %}
  <footer class="text-center text-lg-start bg-light text-muted">
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
      FOOTER
    </div>
  </footer>
  {% endblock %}{# footer #}
        {% block javascripts %}
  <!-- Bootstrap core JS-->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
  <!-- Core theme JS-->
 <script src="{{ asset('js/scripts.js', 'startbootstrap') }}"></script>
{% endblock %} {# javascripts #}

        {% endblock %}
    </body>
</html>