src/Entity/Hall.php
<?php

namespace App\Entity;

use App\Repository\HallRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: HallRepository::class)]
class Hall
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column]
    private ?bool $publie = null;

   

    #[ORM\ManyToMany(targetEntity: Materiel::class, inversedBy: 'halls')]
    private Collection $materiels;

    #[ORM\ManyToOne(inversedBy: 'halls')]
    private ?Membre $membre = null;

    public function __construct()
    {
        
        $this->materiels = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function isPublie(): ?bool
    {
        return $this->publie;
    }

    public function setPublie(bool $publie): self
    {
        $this->publie = $publie;

        return $this;
    }

 

    public function __toString() {
        return $this->description;
    }

    /**
     * @return Collection<int, Materiel>
     */
    public function getMateriels(): Collection
    {
        return $this->materiels;
    }

    public function addMateriel(Materiel $materiel): self
    {
        if (!$this->materiels->contains($materiel)) {
            $this->materiels->add($materiel);
        }

        return $this;
    }

    public function removeMateriel(Materiel $materiel): self
    {
        $this->materiels->removeElement($materiel);
        var_dump($this->materiels->removeElement($materiel));
        return $this;
    }

    public function getMembre(): ?Membre
    {
        return $this->membre;
    }

    public function setMembre(?Membre $membre): self
    {
        $this->membre = $membre;

        return $this;
    }
}

src/Entity/Membre.php
<?php

namespace App\Entity;

use App\Repository\MembreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MembreRepository::class)]
class Membre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 30)]
    private ?string $Nom = null;

    #[ORM\Column(length: 30)]
    private ?string $prenom = null;

    #[ORM\OneToMany(mappedBy: 'proprietaire', targetEntity: Salle::class, orphanRemoval: true,cascade: ["persist"])]
    private Collection $salles;

    #[ORM\OneToMany(mappedBy: 'membre', targetEntity: Hall::class)]
    private Collection $halls;

    #[ORM\OneToOne(inversedBy: 'membre', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $User = null;

  

    public function __construct()
    {
        $this->salles = new ArrayCollection();
        $this->halls = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * @return Collection<int, Salle>
     */
    public function getSalles(): Collection
    {
        return $this->salles;
    }

    public function addSalle(Salle $salle): self
    {
        if (!$this->salles->contains($salle)) {
            $this->salles->add($salle);
            $salle->setProprietaire($this);
        }

        return $this;
    }

    public function removeSalle(Salle $salle): self
    {
        if ($this->salles->removeElement($salle)) {
            // set the owning side to null (unless already changed)
            if ($salle->getProprietaire() === $this) {
                $salle->setProprietaire(null);
            }
        }

        return $this;
    }
    public function __toString() 
    {
        return $this->Nom ;
    }

    /**
     * @return Collection<int, Hall>
     */
    public function getHalls(): Collection
    {
        return $this->halls;
    }

    public function addHall(Hall $hall): self
    {
        if (!$this->halls->contains($hall)) {
            $this->halls->add($hall);
            $hall->setMembre($this);
        }

        return $this;
    }

    public function removeHall(Hall $hall): self
    {
        if ($this->halls->removeElement($hall)) {
            // set the owning side to null (unless already changed)
            if ($hall->getMembre() === $this) {
                $hall->setMembre(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(User $User): self
    {
        $this->User = $User;

        return $this;
    }

   

   
}

src/Form/HallType.php
<?php

namespace App\Form;

use App\Entity\Hall;
use App\Entity\Membre;
use App\Repository\MaterielRepository;
use App\Repository\MembreRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Security\Core\Security ;
class HallType extends AbstractType
{   private $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $hall = $options['data'] ?? null;
       // $membre = $hall->getMembre();
        $membre = $this->security->getUser()->membre;
      //  var_dump($membre);
        $builder
            ->add('description')
            ->add('publie')
            
            ->add('materiels', null, [
                'query_builder' => function (MaterielRepository $er) use ($membre) {
                        return $er->createQueryBuilder('g')
                        ->leftJoin('g.salle', 'i')
                        ->andWhere('i.proprietaire = :membre')
                        ->setParameter('membre', $membre)
                        ;
                    }
                ])
             ->add('membre',null,[
              
                'disabled'   => true,
            ])
            
        ;
           //dump($options);
          // var_dump($options);
   
          
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Hall::class,
        ]);
    }
}

src/Controller/HallController.php
<?php

namespace App\Controller;

use App\Entity\Hall;
use App\Entity\Materiel;
use App\Form\HallType;
use App\Repository\HallRepository;
use App\Repository\UserRepository;
use Doctrine\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
#[Route('/hall')]
#[IsGranted("IS_AUTHENTICATED_FULLY")]
class HallController extends AbstractController
{
    #[Route('/', name: 'app_hall_index', methods: ['GET'])]
    public function index(HallRepository $hallRepository): Response
    {
        $privatehalls = array();
       
        $user = $this->getUser();
        dump($user->membre);
        if($user) {
         
            $member = $user->membre;
            $privatehalls = $hallRepository->findBy(
        [
              'publie' => false,
              'membre' => $member
        ]);
}
if ($this->isGranted('ROLE_ADMIN')) {
    $privatehalls = $hallRepository->findAll();
}

        return $this->render('hall/index.html.twig', [
            'halls' => $privatehalls,
        ]);
    }

    #[Route('/new', name: 'app_hall_new', methods: ['GET', 'POST'])]
    public function new(Request $request, HallRepository $hallRepository): Response
    {  
        $hall = new Hall();
        $form = $this->createForm(HallType::class, $hall);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $hallRepository->save($hall, true);
        
            $this->addFlash('message', 'Hall ajouté');
            var_dump($hall->getId());
            return $this->redirectToRoute('app_hall_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('hall/new.html.twig', [
            'hall' => $hall,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_hall_show', methods: ['GET'])]
    public function show(Hall $hall): Response
    {   $membreUser =$this->getUser();
        $hasAccess = $this->isGranted('ROLE_ADMIN') || ($membreUser== $hall->getMembre()->getUser());
        if(! $hasAccess) {
            throw $this->createAccessDeniedException("You cannot access another member's hall!");
                    }


        return $this->render('hall/show.html.twig', [
            'hall' => $hall,
        ]);
    }
    #[IsGranted('ROLE_USER')]
    #[Route('/{id}/edit', name: 'app_hall_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Hall $hall, HallRepository $hallRepository): Response
    {    



                    $hasAccess = false;
                    if($this->isGranted('ROLE_ADMIN') || $hall->isPublie()) {
                        $hasAccess = true;
                    }
                    else {
                        $user = $this->getUser();
                        if( $user ) {
                            
                            if ( $user &&  ($user == $hall->getMembre()->getUser()) ) {
                                $hasAccess = true;
                            }
                        }
                    }
                    if(! $hasAccess) {
                        throw $this->createAccessDeniedException("You cannot access the requested resource!");
                    }


        $form = $this->createForm(HallType::class, $hall);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $hallRepository->save($hall, true);
            $this->addFlash('message', 'Hall modifié');
            return $this->redirectToRoute('app_hall_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('hall/edit.html.twig', [
            'hall' => $hall,
            'form' => $form,
        ]);
    }
    #[IsGranted('ROLE_ADMIN')]
    #[Route('/{id}', name: 'app_hall_delete', methods: ['POST'])]
    public function delete(Request $request, Hall $hall, HallRepository $hallRepository): Response
    {    $membreUser =$this->getUser();
        $hasAccess = $this->isGranted('ROLE_ADMIN') || ($membreUser== $hall->getMembre()->getUser());
        if(! $hasAccess) {
            throw $this->createAccessDeniedException("You cannot access another member's hall!");
                    }
        if ($this->isCsrfTokenValid('delete'.$hall->getId(), $request->request->get('_token'))) {
            $hallRepository->remove($hall, true);
        }
        $this->addFlash('message', 'Hall suprime');

        return $this->redirectToRoute('app_hall_index', [], Response::HTTP_SEE_OTHER);
    }

#[Route('/{hall_id}/materiel/{materiel_id}', name: 'app_hall_materiel_show', methods: ['GET'])]
#[ParamConverter(
    'hall',
    class: Hall::class,
    options: ['id' => 'hall_id'],
)]
#[ParamConverter(
    'materiel',
    class: Materiel::class,
    options: ['id' => 'materiel_id'],
)]
public function materielShow(Hall $hall, Materiel $materiel): Response
{ 
    $hasAccess = false;
    if($this->isGranted('ROLE_ADMIN') || $hall->isPublie()) {
        $hasAccess = true;
    }
    else {
        $user = $this->getUser();
        if( $user ) {
            
            if ( $user &&  ($user == $hall->getMembre()->getUser()) ) {
                $hasAccess = true;
            }
        }
    }
    if(! $hasAccess) {
        throw $this->createAccessDeniedException("You cannot access the requested resource!");
    }
    if(! $hall->getMateriels()->contains($materiel)) {
        throw $this->createNotFoundException("Couldn't find such a materiel in this hall !");
    }

    if(! $hall->isPublie()) {
        throw $this->createAccessDeniedException("You cannot access the requested ressource!");
    }
    return $this->render('hall/materiel_show.html.twig', [
        'materiel' => $materiel,
        'hall' => $hall
    ]);
}
}

templates/hall/_delete_form.html.twig
<form method="post" action="{{ path('app_hall_delete', {'id': hall.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ hall.id) }}">
    <button class="btn">Delete</button>
</form>

templates/hall/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/hall/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Hall{% endblock %}

{% block main %}
    <h1>Edit Hall</h1>

    {{ include('hall/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_hall_index') }}">back to list</a>
    {% if is_granted('ROLE_ADMIN') %}
    {{ include('hall/_delete_form.html.twig') }}
    {% endif %}
{% endblock %}

templates/hall/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hall index{% endblock %}

{% block main %}
    <h1>Hall index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Description</th>
                <th>Publie</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for hall in halls %}
            <tr>
                <td>{{ hall.id }}</td>
                <td>{{ hall.description }}</td>
                <td>{{ hall.publie ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_hall_show', {'id': hall.id}) }}">show</a>
                     {% if is_granted('ROLE_USER') %}

                    <a href="{{ path('app_hall_edit', {'id': hall.id}) }}">edit</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_hall_new') }}">Create new</a>
    {% block alerts %}
  {% for type, messages in app.session.flashBag.all %}
    {% for message in messages %}
        {%if type == 'error'%} {% set type = 'danger' %} {%endif%}
        {%if type == 'message'%} {% set type = 'info' %} {%endif%}
        {# Bootstrap alert, see http://getbootstrap.com/components/#alerts #}
        <div class="alert alert-{{ type }} alert-dismissible fade show" role="alert">
            <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                <span class="sr-only">Close</span>
            </button>
            <p>{{ message|raw }}</p>
        </div>
    {% endfor %}
  {% endfor %}
{% endblock %} {# alerts #}

{% endblock %}

templates/hall/materiel_show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Materielofhall{% endblock %}

{% block main %}
    <h1>Materiel du hall</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ hall.id }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ hall.description }}</td>
            </tr>
            <tr>
                <th>Publie</th>
                <td>{{ hall.publie ? 'Yes' : 'No' }}</td>
            </tr>
             
                
                
           
        </tbody>
    </table>
     <h1>Materiel</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ materiel.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ materiel.nom }}</td>
            </tr>
            <tr>
                <th>Marque</th>
                <td>{{ materiel.marque }}</td>
            </tr>
            <tr>
                <th>Type materiel</th>
                <td>{{ materiel.type|join(', ') }}</td>
            </tr>
        </tbody>
    </table>

 <a href="{{ path('app_hall_show', { 'id': hall.id}) }}">back to Hall</a>


{% endblock %}

templates/hall/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Hall{% endblock %}

{% block main %}
    <h1>Create new Hall</h1>

    {{ include('hall/_form.html.twig') }}

    <a href="{{ path('app_hall_index') }}">back to list</a>
{% endblock %}

templates/hall/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hall{% endblock %}

{% block main %}
    <h1>Hall</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ hall.id }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ hall.description }}</td>
            </tr>
            <tr>
                <th>Publie</th>
                <td>{{ hall.publie ? 'Yes' : 'No' }}</td>
            </tr>
             <tr>
                <th>Materiels</th>
                <td><ul>
               {% for materiel in hall.materiels %}
   <li>
     <a href="{{ path('app_hall_materiel_show', {'hall_id': hall.id, 'materiel_id' : materiel.id}) }}">{{ materiel }}</a>
   </li>
   {% endfor %}
</ul></td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_hall_index') }}">back to list</a>

    <a href="{{ path('app_hall_edit', {'id': hall.id}) }}">edit</a>

    {{ include('hall/_delete_form.html.twig') }}


{% endblock %}